Report : MECHANICAL
Part Failure : LANDING GEAR GND FAIL MSG AFTER TAKEOFF EMERGENCY DECLARED- BRAKE OVERHEAT CAUTION MESSAGE. ERRATIC RT INBOARD - PEGGED AT MAX TEMP -MEL 3203 AUTH 060159DM-C AML 4764592 ITEM 1.-C/A-TROUBLESHOT RH MLG BRAKE TEMP INDICATION HARNESS IAW SWPM 20-20-03. NO TIME TO FIX. UPDATED KVA. MEL CONTINUES. M PROCEDURES RE-COMPLIED WITH.,RT MLG BRAKE DAMAGED
Occurence Nature condition : WARNING INDICATION
Occurence Precautionary Procedures : OTHER